import { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { motion, Variants } from 'framer-motion';
import { ShieldAlert, FileDown, ExternalLink, AlertTriangle, Hash, Activity, Home, Copy, CheckCircle, FileText, Download } from 'lucide-react';
import { generatePDFReport, ReportData } from '../services/reportPDF';
import { reportToCommunityDB } from '../services/api';
import InvestigationPanel from './InvestigationPanel';
import { exportToHTML, exportToCSV, ExportableReport } from '../services/reportExport';

const ReportView = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const report = location.state?.report as ReportData;
  const reportId = location.state?.reportId as string | undefined;
  const [copied, setCopied] = useState(false);
  const [isReporting, setIsReporting] = useState(false);

  useEffect(() => {
    if (!report) {
      const timer = setTimeout(() => navigate('/app'), 2000);
      return () => clearTimeout(timer);
    }
  }, [report, navigate]);

  if (!report) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <p className="text-white/50">No report data found. Returning home...</p>
      </div>
    );
  }

  const containerVariants: Variants = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const itemVariants: Variants = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0, transition: { type: "spring", stiffness: 300, damping: 24 } }
  };

  const handleCopyFIR = () => {
    navigator.clipboard.writeText(report.formalComplaintText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadAndReport = async () => {
    setIsReporting(true);
    // PDF Generation and Sanchar Saathi Integration:
    // Browser security restrictions block programmatic file downloads if they occur after an asynchronous delay
    // (like an API call). Therefore, `generatePDFReport` MUST execute synchronously in the UI thread immediately
    // after the user click event, *before* we await the async database post (`reportToCommunityDB`).
    try {
      generatePDFReport(report);
    } catch (err) {
      console.error('Error generating PDF:', err);
    }

    await reportToCommunityDB(report.callerNumber, report.peakRiskScore);

    setTimeout(() => setIsReporting(false), 1500);
  };

  return (
    <div className="min-h-screen bg-transparent text-white px-4 sm:px-8 pt-4 sm:pt-6 pb-28 max-w-5xl mx-auto">

      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        className="flex flex-col items-center justify-center text-center mt-6 mb-8"
      >
        <div className="relative mb-4">
          <div className="w-16 h-16 rounded-2xl bg-danger/10 border border-danger/30 flex items-center justify-center p-1.5 shadow-[0_0_30px_rgba(226,75,74,0.2)] overflow-hidden">
            <img
              src="/Dhwani_AI_transparent_512x512.png"
              alt="Dhwani AI"
              className="w-full h-full object-contain drop-shadow-[0_2px_8px_rgba(255,109,0,0.5)]"
            />
          </div>
          <div className="absolute -bottom-1 -right-1 w-6 h-6 rounded-full bg-danger flex items-center justify-center border-2 border-background shadow-sm">
            <ShieldAlert className="w-3.5 h-3.5 text-white" />
          </div>
        </div>
        <h1 className="text-3xl sm:text-4xl font-serif italic font-normal text-white mb-1 tracking-wide">Incident Report</h1>
        <p className="text-white/50 text-sm">
          Auto-generated by{' '}
          <span className="font-brand text-white font-black" style={{ fontFamily: "'Outfit', sans-serif" }}>Dhwani AI</span>
        </p>
      </motion.div>

      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="show"
        className="space-y-4"
      >
        {/* Quick Stats */}
        <motion.div variants={itemVariants} className={`grid ${report.finalRiskScore !== undefined ? 'grid-cols-3' : 'grid-cols-2'} gap-3`}>
          <div className="glass-card p-4 flex flex-col">
            <span className="text-white/40 text-[10px] uppercase tracking-wider mb-2 flex items-center gap-1">
              <Hash className="w-3 h-3" /> Caller
            </span>
            <span className="font-mono text-base sm:text-lg text-white font-medium truncate">{report.callerNumber}</span>
          </div>

          {report.finalRiskScore !== undefined && (
            <div className="glass-card p-4 flex flex-col">
              <span className="text-white/40 text-[10px] uppercase tracking-wider mb-2 flex items-center gap-1">
                <CheckCircle className="w-3 h-3 text-emerald-400" /> Resolved Risk
              </span>
              <span className={`text-2xl font-bold leading-none ${report.finalRiskScore < 40 ? 'text-emerald-400' : report.finalRiskScore < 70 ? 'text-warning' : 'text-danger'}`}>
                {report.finalRiskScore}<span className="text-sm opacity-60 font-normal">/100</span>
              </span>
              {report.livenessScore ? (
                <span className="text-[10px] text-emerald-400/80 mt-1 font-mono">Liveness Verified ({report.livenessScore}%)</span>
              ) : (
                <span className="text-[10px] text-white/40 mt-1 font-mono">{report.finalRiskScore < 40 ? 'Safe State' : 'Elevated'}</span>
              )}
            </div>
          )}

          <div className="glass-card p-4 flex flex-col">
            <span className="text-white/40 text-[10px] uppercase tracking-wider mb-2 flex items-center gap-1">
              <Activity className="w-3 h-3 text-orange-400" /> Peak Risk
            </span>
            <span className={`text-2xl font-bold leading-none ${report.peakRiskScore >= 70 ? 'text-danger' : report.peakRiskScore >= 40 ? 'text-warning' : 'text-emerald-400'}`}>
              {report.peakRiskScore}<span className="text-sm opacity-60 font-normal">/100</span>
            </span>
            <span className="text-[10px] text-white/40 mt-1 font-mono">Session Max</span>
          </div>
        </motion.div>

        {/* Summary */}
        <motion.div variants={itemVariants} className="glass-card-strong p-5 relative overflow-hidden">
          <div className="absolute top-0 left-0 w-1 h-full bg-warning" />
          <div className="inline-block px-3 py-1 bg-warning/20 text-warning text-xs font-bold rounded-full uppercase tracking-wide mb-3">
            {report.scamType}
          </div>
          <p className="text-white/90 leading-relaxed text-sm">
            {report.summary}
          </p>
        </motion.div>

        {/* Red Flags */}
        <motion.div variants={itemVariants}>
          <h3 className="text-sm font-bold text-white/70 uppercase tracking-widest mb-3 ml-2 mt-6">Detected Red Flags</h3>
          <div className="space-y-2">
            {report.redFlags.map((flag, idx) => (
              <div key={idx} className="glass-card p-3 px-4 flex gap-3 items-start border-l-2 border-l-danger/50">
                <AlertTriangle className="w-4 h-4 text-danger shrink-0 mt-0.5" />
                <span className="text-sm text-white/80">{flag}</span>
              </div>
            ))}
          </div>
        </motion.div>

        {/* FIR Template */}
        <motion.div variants={itemVariants}>
          <h3 className="text-sm font-bold text-white/70 uppercase tracking-widest mb-3 ml-2 mt-6">Cyber Police FIR Template</h3>
          <div className="relative group">
            <div className="bg-[#09121c] border border-white/5 rounded-xl p-5 text-sm text-white/60 font-mono leading-relaxed whitespace-pre-wrap selection:bg-primary/30">
              {report.formalComplaintText}
            </div>
            {/*
             * Formal Police Complaint Action:
             * Copies the LLM-generated formal complaint directly to the user's system clipboard using the
             * `navigator.clipboard` API to facilitate easy pasting into official government portals.
             */}
            <button
              onClick={handleCopyFIR}
              className="absolute top-3 right-3 p-2 bg-white/10 hover:bg-white/20 rounded-lg backdrop-blur-md transition-all text-white"
              title="Copy to clipboard"
            >
              {copied ? <CheckCircle className="w-4 h-4 text-primary" /> : <Copy className="w-4 h-4" />}
            </button>
          </div>
        </motion.div>

        {/* Action Buttons */}
        <motion.div variants={itemVariants} className="pt-8 space-y-3 pb-8">
          <button
            onClick={handleDownloadAndReport}
            disabled={isReporting}
            className={`w-full py-3.5 px-4 rounded-xl font-bold transition-all flex items-center justify-center gap-2 active:scale-[0.98] ${isReporting
                ? 'bg-amber-400 text-slate-950 font-black shadow-[0_0_20px_rgba(255,109,0,0.5)]'
                : 'bg-gradient-to-r from-orange-500 via-amber-500 to-yellow-400 hover:opacity-95 text-slate-950 font-black shadow-[0_0_20px_rgba(255,109,0,0.35)]'
              }`}
          >
            {isReporting ? <CheckCircle className="w-5 h-5" /> : <FileDown className="w-5 h-5" />}
            {isReporting ? 'Saved & Flagged in Community DB!' : 'Download PDF Report'}
          </button>

          <button
            onClick={() => {
              handleCopyFIR();
              // Standard browser tabs are launched to redirect victims to the government cybercrime reporting portal (Chakshu).
              // We introduce a small artificial delay (400ms) to allow the copy success UI state to render before the browser switches tabs.
              setTimeout(() => {
                window.open('https://sancharsaathi.gov.in/sfc/Home/sfc-complaint.jsp', '_blank');
              }, 400);
            }}
            className="w-full py-3.5 px-4 bg-transparent border border-white/20 hover:border-white/40 hover:bg-white/5 text-white rounded-xl font-medium transition-all flex items-center justify-center gap-2 active:scale-[0.98]"
          >
            <ExternalLink className="w-5 h-5 text-white/60" />
            {copied ? 'Copied Details & Opening Portal...' : 'Report to Sanchar Saathi (Chakshu)'}
          </button>
        </motion.div>


        {/* Investigation Panel (only when reportId is available from dashboard) */}
        {reportId && (
          <motion.div variants={itemVariants} className="mt-6">
            <InvestigationPanel
              reportId={reportId}
              currentStatus="Needs Review"
              currentNotes=""
            />
          </motion.div>
        )}

        {/* Additional Export Options */}
        <motion.div variants={itemVariants} className="flex gap-3 mt-4">
          <button
            onClick={() => {
              const exportable: ExportableReport = {
                callerNumber: report.callerNumber,
                peakRiskScore: report.peakRiskScore,
                scamType: report.scamType,
                summary: report.summary || '',
                redFlags: report.redFlags,
                formalComplaintText: report.formalComplaintText,
                createdAt: report.createdAt,
              };
              exportToHTML(exportable);
            }}
            className="flex-1 py-3 px-4 glass-card hover:bg-white/10 rounded-xl font-medium transition-all flex items-center justify-center gap-2 text-sm text-white/80 active:scale-[0.98]"
          >
            <Download className="w-4 h-4" /> Export HTML
          </button>
          <button
            onClick={() => {
              const exportable: ExportableReport = {
                callerNumber: report.callerNumber,
                peakRiskScore: report.peakRiskScore,
                scamType: report.scamType,
                summary: report.summary || '',
                redFlags: report.redFlags,
                formalComplaintText: report.formalComplaintText,
                createdAt: report.createdAt,
              };
              exportToCSV([exportable]);
            }}
            className="flex-1 py-3 px-4 glass-card hover:bg-white/10 rounded-xl font-medium transition-all flex items-center justify-center gap-2 text-sm text-white/80 active:scale-[0.98]"
          >
            <FileText className="w-4 h-4" /> Export CSV
          </button>
        </motion.div>

        {/* Dashboard Navigation */}
        <motion.div variants={itemVariants} className="mt-4">
          <button
            onClick={() => navigate('/dashboard')}
            className="w-full py-3.5 px-4 bg-[#132238] border border-amber-500/30 hover:bg-amber-500/10 hover:border-amber-500/50 text-amber-300 rounded-xl font-medium transition-all flex items-center justify-center gap-2 active:scale-[0.98] shadow-[0_0_15px_rgba(255,109,0,0.15)]"
          >
            <ShieldAlert className="w-5 h-5" />
            Open Security Dashboard
          </button>
        </motion.div>

        <motion.div variants={itemVariants} className="text-center">
          <button
            onClick={() => navigate('/app')}
            className="text-white/40 hover:text-white flex items-center justify-center gap-2 mx-auto text-sm transition-colors py-4"
          >
            <Home className="w-4 h-4" /> Return to Home
          </button>
        </motion.div>

      </motion.div>
    </div>
  );
};

export default ReportView;

